spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/campusShop?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 1234567
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.springboot.servie.*
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
  devtools:
    restart:
      # 设置开启热部署
      enabled: true
      additional-paths: src/main
  # 模板配置
  thymeleaf:
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
  servlet:
    multipart:
      # 是否支持批量上传   (默认值 true)
      enabled: true
      resolve-lazily: false
# 开启日志
debug: true
# 日志记录级别
logging:
  level:
    # root日志以WARN级别输出
    root: warn
    cn:
      fanchencloud:
        campus: debug
    # 去掉 CONDITIONS EVALUATION REPORT
    org:
      springframework:
        boot:
          autoconfigure: error
  config: classpath:log4j2.xml
# MyBatis 配置
mybatis-plus:
  # mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wjj.campus.entity
  configuration:
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#支付宝支付
#配置路径(页面上沙箱应用里的网关地址)、商户编号、私钥(工具生成的私钥)、公钥(支付宝公钥)、异步通知、支付成功以后自动访问的请求
alipay:
  url: https://openapi.alipaydev.com/gateway.do
  appid: 2021000119662618
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCJ3NMrL9KdVV261olKY7TaCXN97aiaP0cHAr02FiXOCFravokSvlQTu55docAq9ysr1RA9BZ6inx87qZVRXQCXxeDBIKH4SC9GJOWTi61DR5HCkBcyFdKy926KljfhYmFtWi1ePWiCNc39CVuMZYm1Kgu0dxJsY60Miao8ZJilAjrvnj1IsoPxxfKwQQRe49/CENUOtr2/UTVtL9D2zvXYv1zpQpOl4Y0Yo2Wv1Rmh2C7EIYbMP07m0Ek7E5Tb0Hy7bRQ0XYL16QM11jxgD7aZApsFNs7b0c5trpsdOjrbXdyjsystMpkiNDRYQFMuZdeEm+yxPOvAVWLb6KC+dH75AgMBAAECggEAZal57zbs0SjKXaUmyLyN+NtPV2WSF2ziK8FRVjku16hBl106J6BCz+pi9hj5ZLWwGDqeJuGmAbXlilGb0swKS+GXw9MUncpdUhSTVyKBOkPksN0gvcZqAZ+E3J25x3KM9d6x5fTSxHJ43EeyQu39hqLizsmfxF4clkpORwrHpaXOZHtIz3y3v57k0tGVQUiQFSAA23zVuF0BCGC40f7KQgyWTTnVhWtkyC7gsly1Dck+udyhTr44YQ2AqjFmKOTsXcqgWDsZzIiY6cowqczUyVSO12DRJtne1LS2KOsqsKE4IzgypFuC3jUb4mNjx0EPGOoWuH+2PA5OAnzum14cAQKBgQDeMeb5SCR6NKd6BzIL6CgY+lKy9Y6nQW6HnG7r4BLlGtNgcGJq2sntvCabt+BDkW4ybRbJz63ptKzPvF+K8rl54DFnvY03WbCP7Plbj/REU3ecAhYJCVlbMqvapYO5tUmwU8ptFo+jIvSJicHmuUdCOtVZXnNl6siRrdJAahaG8QKBgQCe1lP9jof7b0eNtnVEujWad09/TzMZeRUZrdNSk6oTMf+wkLDaGl/9rHncOf5fxsWJ58jIXj/op0eyqcozN0052PM3/yo1cu66S8U4APs0dAYEE51Q8qk9CapA1yObO6DGtfOPXV+rkuP+lrq8aLhAT8l1hMISNaMjjpCAUprIiQKBgQCjRgwyFf8oBdUjaHIwKbJ9WES42JSw9vXflOY1UfzQebvl2++WEZvcpCvCtYWIYS+Wwm7CcWecmnV6WTPkCKSemE31q2Y/zBpgSISb8dZO9v6nlyjWDxaoWz3Jd2Kqbjrt5USUkMWP3TnQb3gasP9Z/Z2VBEDMHZCw7AfZ6ZsQIQKBgBNRmCeXxVxEfZxz27F/QHPIHSgr1tg7TOCxrqk1gpMRGrs77fapDJHK/4tUlmbJw07xnQ8Zv4YpimPlmM0/5amqhHKEG3sivnx0KMmV/Pe1QOIQDKtCyGi/GzEFubPwva5NhREj1zYECKz3YkD2L6rKyYL8oaobUftKJLMm2OKZAoGBAMUZMPPuZ+V24wxomEUcdK0qd7dbu5Rk3gFPUxHCMdOBSyfMwZK2ohbBFUsXntOSc7Jjhc2jxJQ+pepG2WhY1kO2wbDZsPa7HfaEVXk+ehpOsIowANrKg7BqS5AsoRYlKB8XriYD5rk81cTcMZr+UhcxlQISjGWYN0QihHxggvAk
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq1oBxnbdmZUW5HE0Jub/srQhhAMgcGtO20pcc6CpSJ/UgFgf5bJPQuLmEx5s30l7hexRXpVM/UoSVaKLmZiZfAE0ultYUc0seTw68Z0Y0HrhssKEC55TOUaT8iAIH4sPptug1QJqpD69iunT6UNW8/eDMHB6Vq1wssYAQO4rn3Vy4b0qWFpz7aZQOPzHAPn0+2QMJEcgOcc/m7bmgtBg6zkqwvl7p+9xDowETDFEhB1xK/k7oBzemy9GZUMiKPe9qLVH3+QuNDBx3DnAvu+pFpLmwzkz5k0ZrcorWuIdAhJo1uqekH5XTZ2c9utw6Dd/SW9V5/nlxtLu/xuuqBEV0wIDAQAB
  notifyUrl: http://localhost:8080/
  returnUrl: http://localhost:8080/product/productDetail?



